/// <summary>
/// Author: SmallBurger Inc
/// Date: 2025/09/19
/// Desc:
/// </summary>

#pragma kernel CSMain

#pragma multi_compile_local _ PROCESS_WEIGHT_MAP_FILTER
#define PROCESS_WEIGHT_MAP_FILTER

#include "GrassParams.hlsl"
#include "SimplexNoise.hlsl"

static const float3 s_cRandomVector = float3(0.1031, 0.1030, 0.0973);
static const half sc_widthWorldScale = 100.0;
static const half sc_heightWorldScale = 200.0;
static const half sc_noiseScale = 500.0;
static const float sc_PI = 3.1415927;
static const float sc_towPI = 2.0 * sc_PI;
static const float sc_skipWeightRatio = 0.3;

StructuredBuffer<uint> _VisibleCellIndexBuffer;

RWTexture2D<float4> _FilterResultRT;
RWStructuredBuffer<uint> _InstanceCountBuffer;
float2 _FilterResultRTSize;

SamplerState sampler_WeightMap;
Texture2D<float4> _WeightMap;

half2 _CellSize;
uint _CellColumnCount;
uint _CellInstanceColumnCount;
uint _CellInstanceCount;

uint _MaxProcessCount;
uint _OffsetCount;
half _JitterStrength;
half2 _InstanceSpacing;
float4x4 _ViewProjectionMatrix;
float3 _CameraPosition;

//x:baseSize
//y:minSizeOffest
//z:maxSizeOffest
half3 _WidthSizeInfo;
half3 _HeightSizeInfo;

half _WindWeight;
//x:intensity
//y:frequency
half2 _WindAParams;
//xy:tiling
//zw:wrap
half4 _WindATilingWrap;

half2 _WindBParams;
half4 _WindBTilingWrap;

half2 _WindCParams;
half4 _WindCTilingWrap;

float _CurrentTime;

float2 GetRandomOffest2D(in float2 point2D)
{
	float3 point3D = frac(float3(point2D.xyx) * s_cRandomVector);
	point3D += dot(point3D, point3D.yzx + 33.33);
	return frac((point3D.xx + point3D.yz) * point3D.zy);
}

half2 GetDestSize(in float2 position2D, in half grassWeight)
{
	half2 baseSize = half2(_WidthSizeInfo.x, _HeightSizeInfo.x) * grassWeight;

	half sizeOffest = sc_noiseScale *
		GetSimplexNoise(position2D * sc_widthWorldScale);
	half destWidth = clamp(baseSize.x + sizeOffest,
		baseSize.x - _WidthSizeInfo.y,
		baseSize.x + _WidthSizeInfo.z);

	sizeOffest = sc_noiseScale *
		GetSimplexNoise(position2D * sc_heightWorldScale);
	half destHeight = clamp(baseSize.y + sizeOffest,
		baseSize.y - _HeightSizeInfo.y,
		baseSize.y + _HeightSizeInfo.z);

	return half2(destWidth, destHeight);
}

half CalculateWind(in float2 position2D)
{
	half wind = 0;	
	
	wind += (sin(_CurrentTime * _WindAParams.y +
		position2D.x * _WindATilingWrap.x +
		position2D.y * _WindATilingWrap.y) *
		_WindATilingWrap.z + _WindATilingWrap.w) *
		_WindAParams.x;
	
	wind += (sin(_CurrentTime * _WindBParams.y +
		position2D.x * _WindBTilingWrap.x +
		position2D.y * _WindBTilingWrap.y) *
		_WindBTilingWrap.z + _WindBTilingWrap.w) *
		_WindBParams.x;
	
	wind += (sin(_CurrentTime * _WindCParams.y +
		position2D.x * _WindCTilingWrap.x +
		position2D.y * _WindCTilingWrap.y) *
		_WindCTilingWrap.z + _WindCTilingWrap.w) *
		_WindCParams.x;

	return wind * _WindWeight;
}

void GetInstanceTransform(in uint instanceOffest, out float2 position2D, out half yawRadians)
{
	uint destCellIndex = _VisibleCellIndexBuffer[instanceOffest / _CellInstanceCount];

	uint destCellColumnIndex = destCellIndex % _CellColumnCount;
	uint destCellRowIndex = destCellIndex / _CellColumnCount;

	float2 worldOrigion = float2(
		_WorldMinMax.x + destCellColumnIndex * _CellSize.x,
		_WorldMinMax.y + destCellRowIndex * _CellSize.y);

	uint offestInstanceIndex = instanceOffest % _CellInstanceCount;

	uint2 instanceIndex = uint2(
		offestInstanceIndex % _CellInstanceColumnCount,
		offestInstanceIndex / _CellInstanceColumnCount);

	float2 nonOffestTransform = float2(
		worldOrigion.x + instanceIndex.x * _InstanceSpacing.x,
		worldOrigion.y + instanceIndex.y * _InstanceSpacing.y);

	float2 randomOffest2D = GetRandomOffest2D(nonOffestTransform);

	float2 instanceRandomOffest = randomOffest2D * 2.0 - 1.0;

	position2D = nonOffestTransform + instanceRandomOffest * _JitterStrength;	

	yawRadians = instanceRandomOffest.x * sc_towPI;
}

half2 GetWorldUV(in float2 worldPosition2D)
{
	float2 clmapPosition2D = clamp(worldPosition2D, _WorldMinMax.xy, _WorldMinMax.zw);
	return half2((clmapPosition2D.x - _WorldMinMax.x) / (_WorldMinMax.z - _WorldMinMax.x),
		(clmapPosition2D.y - _WorldMinMax.y) / (_WorldMinMax.w - _WorldMinMax.y));
}

[numthreads(64, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{	
	uint instanceIndex = id.x + _OffsetCount;
	if (instanceIndex >= _MaxProcessCount)
		return;

	float2 position2D;
	half yawRadians;
	GetInstanceTransform(instanceIndex, position2D, yawRadians);	

	if ((position2D.x < _WorldMinMax.x) ||
		(position2D.y < _WorldMinMax.y) ||
		(position2D.x > _WorldMinMax.z) ||
		(position2D.y > _WorldMinMax.w))
		return;

	float3 delta = _CameraPosition - float3(position2D.x, 0.0f, position2D.y);
	float viewSquareDistance = dot(delta, delta);
	if(viewSquareDistance > _MaxViewSquareDistance)
		return;

	half grassWeight = 1.0;
#ifdef PROCESS_WEIGHT_MAP_FILTER
	grassWeight = _WeightMap.SampleLevel(sampler_WeightMap, GetWorldUV(position2D), 0).a;
	if (grassWeight <= sc_skipWeightRatio)
		return;
#endif

	float4 absPosCS = abs(mul(_ViewProjectionMatrix,
		float4(position2D.x, 0.0, position2D.y, 1.0)));

	//do culling test in clip space, result is the same as doing
	//test in NDC space.
	//prefer clip space here because doing culling test in clip space
	//is faster.
	if ((absPosCS.z > absPosCS.w) ||
		(absPosCS.y > absPosCS.w * _MaxInstanceSize) ||
		(absPosCS.x > absPosCS.w * _MaxInstanceSize))
		return;

	uint index = _InstanceCountBuffer.IncrementCounter();
	uint offestIndex = index * 2;

	half2 worldUV = GetWorldUV(position2D);

	_FilterResultRT[int2(offestIndex % _FilterResultRTSize.x, offestIndex / _FilterResultRTSize.x)] =
		float4(worldUV, GetDestSize(position2D, grassWeight));

	++offestIndex;

	_FilterResultRT[int2(offestIndex % _FilterResultRTSize.x, offestIndex / _FilterResultRTSize.x)] =
		float4(sin(yawRadians), cos(yawRadians), CalculateWind(position2D), 0.0);
}