/// <summary>
/// Author: SmallBurger Inc
/// Date: 2025/09/19
/// Desc:
/// </summary>

#pragma kernel CSMain

#include "GrassInstance.hlsl"
#include "SimplexNoise.hlsl"

static const float3 s_cRandomVector = float3(0.1031, 0.1030, 0.0973);
static const half sc_widthWorldScale = 100.0;
static const half sc_heightWorldScale = 200.0;
static const half sc_noiseScale = 500.0;
static const float sc_PI = 3.1415927;
static const float sc_towPI = 2.0 * sc_PI;


StructuredBuffer<uint> _VisibleCellIndexBuffer;
AppendStructuredBuffer<GrassInstanceData> _VisibleInstanceBuffer;

half2 _CellSize;
uint _CellColumnCount;
uint _CellInstanceColumnCount;
uint _CellInstanceCount;

uint _MaxProcessCount;
uint _OffsetCount;
half _JitterStrength;
half2 _InstanceSpacing;
half _MaxInstanceSize;
float4x4 _ViewProjectionMatrix;
float3 _CameraPosition;

//x:baseSize
//y:minSizeOffest
//z:maxSizeOffest
half3 _WidthSizeInfo;
half3 _HeightSizeInfo;

float4 _WorldMinMax;

half _WindWeight;
//x:intensity
//y:frequency
half2 _WindAParams;
//xy:tiling
//zw:wrap
half4 _WindATilingWrap;

half2 _WindBParams;
half4 _WindBTilingWrap;

half2 _WindCParams;
half4 _WindCTilingWrap;

float _CurrentTime;

half2 GetWorldUV(in float2 worldPosition2D)
{
	float2 clmapPosition2D = clamp(worldPosition2D, _WorldMinMax.xy, _WorldMinMax.zw);
	return half2((clmapPosition2D.x - _WorldMinMax.x) / (_WorldMinMax.z - _WorldMinMax.x),
		(clmapPosition2D.y - _WorldMinMax.y) / (_WorldMinMax.w - _WorldMinMax.y));
}

float2 GetRandomOffest2D(in float2 point2D)
{
	float3 point3D = frac(float3(point2D.xyx) * s_cRandomVector);
	point3D += dot(point3D, point3D.yzx + 33.33);
	return frac((point3D.xx + point3D.yz) * point3D.zy);
}


float2 GetDestBaseSize(in float2 position2D, in float2 sourceSize)
{
	//#if !defined(PROCESS_SIZE_WITH_WEIGHT_MAP)
	return sourceSize;
	//#endif
		/*
		half4 weightColor = SAMPLE_TEXTURE2D_LOD(_WeightMap,
			sampler_WeightMap, GetGroundUV(position2D),0);

		half destWeight = max(weightColor.r, weightColor.g);
		destWeight = max(destWeight, weightColor.b);
		destWeight = max(destWeight, weightColor.a);

		return sourceSize * destWeight;
		*/
}

float2 GetDestSize(in float2 position2D)
{
	float2 baseSize = GetDestBaseSize(position2D,
		float2(_WidthSizeInfo.x, _HeightSizeInfo.x));

	float sizeOffest = sc_noiseScale *
		GetSimplexNoise(position2D * sc_widthWorldScale);
	float destWidth = clamp(baseSize.x + sizeOffest,
		baseSize.x - _WidthSizeInfo.y,
		baseSize.x + _WidthSizeInfo.z);

	sizeOffest = sc_noiseScale *
		GetSimplexNoise(position2D * sc_heightWorldScale);
	float destHeight = clamp(baseSize.y + sizeOffest,
		baseSize.y - _HeightSizeInfo.y,
		baseSize.y + _HeightSizeInfo.z);

	return float2(destWidth, destHeight);
}

half CalculateWind(in float2 position2D)
{
	half wind = 0;	
	
	wind += (sin(_CurrentTime * _WindAParams.y +
		position2D.x * _WindATilingWrap.x +
		position2D.y * _WindATilingWrap.y) *
		_WindATilingWrap.z + _WindATilingWrap.w) *
		_WindAParams.x;
	
	wind += (sin(_CurrentTime * _WindBParams.y +
		position2D.x * _WindBTilingWrap.x +
		position2D.y * _WindBTilingWrap.y) *
		_WindBTilingWrap.z + _WindBTilingWrap.w) *
		_WindBParams.x;
	
	wind += (sin(_CurrentTime * _WindCParams.y +
		position2D.x * _WindCTilingWrap.x +
		position2D.y * _WindCTilingWrap.y) *
		_WindCTilingWrap.z + _WindCTilingWrap.w) *
		_WindCParams.x;

	return wind * _WindWeight;
}

void GetInstanceTransform(in uint instanceOffest, out float2 position2D, out half yawRadians)
{
	uint destCellIndex = _VisibleCellIndexBuffer[instanceOffest / _CellInstanceCount];

	uint destCellColumnIndex = destCellIndex % _CellColumnCount;
	uint destCellRowIndex = destCellIndex / _CellColumnCount;

	float2 worldOrigion = float2(
		_WorldMinMax.x + destCellColumnIndex * _CellSize.x,
		_WorldMinMax.y + destCellRowIndex * _CellSize.y);

	uint offestInstanceIndex = instanceOffest % _CellInstanceCount;

	uint2 instanceIndex = uint2(
		offestInstanceIndex % _CellInstanceColumnCount,
		offestInstanceIndex / _CellInstanceColumnCount);

	float2 nonOffestTransform = float2(
		worldOrigion.x + instanceIndex.x * _InstanceSpacing.x,
		worldOrigion.y + instanceIndex.y * _InstanceSpacing.y);

	float2 randomOffest2D = GetRandomOffest2D(nonOffestTransform);

	float2 instanceRandomOffest = randomOffest2D * 2.0 - 1.0;

	position2D = nonOffestTransform + instanceRandomOffest * _JitterStrength;	

	yawRadians = instanceRandomOffest.x * sc_towPI;
}

[numthreads(64, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{	
	uint instanceIndex = id.x + _OffsetCount;
	if (instanceIndex >= _MaxProcessCount)
		return;

	float2 position2D;
	half yawRadians;
	GetInstanceTransform(instanceIndex, position2D, yawRadians);

	if ((position2D.x < _WorldMinMax.x) ||
		(position2D.y < _WorldMinMax.y) ||
		(position2D.x > _WorldMinMax.z) ||
		(position2D.y > _WorldMinMax.w))
		return;

	float3 delta = _CameraPosition - float3(position2D.x, 0.0f, position2D.y);
	float viewSquareDistance = dot(delta, delta);
	if(viewSquareDistance > _MaxViewSquareDistance)
		return;

	float4 absPosCS = abs(mul(_ViewProjectionMatrix,
		float4(position2D.x, 0.0, position2D.y, 1.0)));

	//do culling test in clip space, result is the same as doing
	//test in NDC space.
	//prefer clip space here because doing culling test in clip space
	//is faster.
	if ((absPosCS.z > absPosCS.w) ||
		(absPosCS.y > absPosCS.w * _MaxInstanceSize) ||
		(absPosCS.x > absPosCS.w * _MaxInstanceSize))
		return;

	GrassInstanceData grassInstanceData = (GrassInstanceData)0;
	grassInstanceData.position2D = position2D;
	grassInstanceData.wind = CalculateWind(grassInstanceData.position2D);

	grassInstanceData.yawSin = sin(yawRadians);
	grassInstanceData.yawCos = cos(yawRadians);

	grassInstanceData.sizeFactor = GetDestSize(grassInstanceData.position2D);
	
	_VisibleInstanceBuffer.Append(grassInstanceData);	
}